FROM webnicer/protractor-headless
MAINTAINER Zsolt MOLNAR <zsolt@zsoltmolnar.hu>

RUN cd / && \
  npm install -g --silent coffee && \
  npm install \
    chai \
    chai-as-promised \
    coffee-script
