#!/usr/bin/env bash
npm run travis after_success

if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
  echo "Not pushing to docker in pull request."
  exit 0
fi

set -e
make docker-login
make docker-tag
make docker-push
npm run push-to-aws