#!/usr/bin/env bash
set -e
. scripts/common.sh

if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then  
  echo "Dependent projects are not released in pull request."
else
  cd project
  semantic-release pre && npm publish && semantic-release post
fi
