#!/usr/bin/env bash
set -e

# DO NOT REMOVE THIS SECTION UNLESS YOU KNOW WHAT YOU DO
npm run travis script

# ADD YOUR PARTS HERE
npm run lint
npm run unittest
npm run build:prod

if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
  npm run systemtest
fi
