#!/usr/bin/env bash
. scripts/common.sh

if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then  
  echo "Project is not released in pull request."
else
  cd project
  semantic-release pre

  if [ $? -eq 0 ]; then
    npm publish && semantic-release post
  fi
fi
