#!/usr/bin/env bash
set -e
if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then  
  echo "Dependent projects are not released in pull request."
else
  npm run semantic-release
  scripts/notify_dependencies
fi
